version: '3'
services:
    rabbitmq-server:
        image: rabbitmq
        hostname: "rabbitmq-server"
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672"
            - "5672"
        labels:
            NAME: "rabbitmq-server"
    articledb:
        build: articledb/
        hostname: "articledb"
        ports:
            - "5432"
        labels:
            NAME: "articledb"
    creator:
        build: createarticles/
        environment:
            - MQURI=amqp://guest:guest@rabbitmq-server:5672/
            - DBURI=postgres://articlewriter:hu8jmn3@articledb:5432/article_postgres_db?sslmode=disable
            - PORT_NUM=5100
        ports:
            - "5100"
    restserver:
        build: REST/
        environment:
            - PORT_NUM=80
        ports:
            - "80:80"
    readarticle:
        build: readarticles/
        environment:
            - PORT_NUM=5200
        ports:
            - "5200"
        depends_on:
            - articledb
            - rabbitmq-server
